export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const ALL_EVENTS_SUCCESS = "ALL_EVENTS_SUCCESS";
export const EVENT_DETAIL_SUCCESS = "EVENT_DETAIL_SUCCESS";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const SIGNOUT = "SIGNOUT";
